# This Makefile is generated by ChatGPT.
CXX = clang++
CXXFLAGS = -std=c++17 -Wall -g

SRC_DIR = src
OBJ_DIR = build
BIN_DIR = bin
TARGET = $(BIN_DIR)/sysc

# Find all source files in src directory (including subdirectories)
SOURCES = $(wildcard $(SRC_DIR)/**/*cpp)
OBJECTS = $(SOURCES:$(SRC_DIR)/%.cpp=$(OBJ_DIR)/%.o)
DEPS = $(OBJECTS:.o=.d)

# Create the bin and obj directories
$(shell mkdir -p $(BIN_DIR))

# The target to build
$(TARGET): $(OBJECTS)
	$(CXX) $(OBJECTS) -o $(TARGET)

# Rule for compiling source files into object files
$(OBJ_DIR)/%.o: $(SRC_DIR)/%.cpp $(OBJ_DIR)/%.d
	@mkdir -p $(dir $@)
	$(CXX) $(CXXFLAGS) -c $< -o $@

# Generate dependencies for each source file
$(OBJ_DIR)/%.d: $(SRC_DIR)/%.cpp
	@mkdir -p $(dir $@)
	$(CXX) -M $(CXXFLAGS) $< > $@; \
		sed 's|^$(SRC_DIR)/|$(OBJ_DIR)/|' $@ > $@.tmp; \
		mv $@.tmp $@

# Include the generated dependency files
-include $(DEPS)

# Clean up build files
clean:
	rm -rf $(OBJ_DIR) $(BIN_DIR)
