#include "../utils/smt/BvExpr.h"
#include <vector>
using namespace smt;

inline void tsgen_push_1(BvExprContext &ctx, std::vector<BvExpr*> &candidates) {
  candidates.reserve(577);
  auto _x = ctx.create(BvExpr::Var, "x");
  auto _c0 = ctx.create(BvExpr::Var, "c0");
  auto _c1 = ctx.create(BvExpr::Var, "c1");
  candidates.push_back(ctx.create(BvExpr::Minus, _x));
  candidates.push_back(ctx.create(BvExpr::Not, _x));
  candidates.push_back(ctx.create(BvExpr::Add, _x, _x));
  candidates.push_back(ctx.create(BvExpr::Sub, _x, _c0));
  candidates.push_back(ctx.create(BvExpr::Sub, _c0, _x));
  candidates.push_back(ctx.create(BvExpr::Mul, _x, _x));
  candidates.push_back(ctx.create(BvExpr::Div, _x, _c0));
  candidates.push_back(ctx.create(BvExpr::Div, _c0, _x));
  candidates.push_back(ctx.create(BvExpr::Mod, _x, _c0));
  candidates.push_back(ctx.create(BvExpr::Mod, _c0, _x));
  candidates.push_back(ctx.create(BvExpr::MulMod, _x, _x, _c0));
  candidates.push_back(ctx.create(BvExpr::Ite, _x, _x, _c0));
  candidates.push_back(ctx.create(BvExpr::Ite, _x, _c0, _x));
  candidates.push_back(ctx.create(BvExpr::Minus, ctx.create(BvExpr::Not, _x)));
  candidates.push_back(ctx.create(BvExpr::Minus, ctx.create(BvExpr::Mul, _x, _x)));
  candidates.push_back(ctx.create(BvExpr::Minus, ctx.create(BvExpr::Div, _x, _c0)));
  candidates.push_back(ctx.create(BvExpr::Minus, ctx.create(BvExpr::Div, _c0, _x)));
  candidates.push_back(ctx.create(BvExpr::Minus, ctx.create(BvExpr::Mod, _x, _c0)));
  candidates.push_back(ctx.create(BvExpr::Minus, ctx.create(BvExpr::Mod, _c0, _x)));
  candidates.push_back(ctx.create(BvExpr::Minus, ctx.create(BvExpr::MulMod, _x, _x, _c0)));
  candidates.push_back(ctx.create(BvExpr::Minus, ctx.create(BvExpr::Ite, _x, _x, _c0)));
  candidates.push_back(ctx.create(BvExpr::Minus, ctx.create(BvExpr::Ite, _x, _c0, _x)));
  candidates.push_back(ctx.create(BvExpr::Not, ctx.create(BvExpr::Minus, _x)));
  candidates.push_back(ctx.create(BvExpr::Not, ctx.create(BvExpr::Add, _x, _x)));
  candidates.push_back(ctx.create(BvExpr::Not, ctx.create(BvExpr::Sub, _x, _c0)));
  candidates.push_back(ctx.create(BvExpr::Not, ctx.create(BvExpr::Sub, _c0, _x)));
  candidates.push_back(ctx.create(BvExpr::Not, ctx.create(BvExpr::Mul, _x, _x)));
  candidates.push_back(ctx.create(BvExpr::Not, ctx.create(BvExpr::Div, _x, _c0)));
  candidates.push_back(ctx.create(BvExpr::Not, ctx.create(BvExpr::Div, _c0, _x)));
  candidates.push_back(ctx.create(BvExpr::Not, ctx.create(BvExpr::Mod, _x, _c0)));
  candidates.push_back(ctx.create(BvExpr::Not, ctx.create(BvExpr::Mod, _c0, _x)));
  candidates.push_back(ctx.create(BvExpr::Not, ctx.create(BvExpr::MulMod, _x, _x, _c0)));
  candidates.push_back(ctx.create(BvExpr::Not, ctx.create(BvExpr::Ite, _x, _x, _c0)));
  candidates.push_back(ctx.create(BvExpr::Not, ctx.create(BvExpr::Ite, _x, _c0, _x)));
  candidates.push_back(ctx.create(BvExpr::Add, ctx.create(BvExpr::Minus, _x), _x));
  candidates.push_back(ctx.create(BvExpr::Add, ctx.create(BvExpr::Minus, _x), _c0));
  candidates.push_back(ctx.create(BvExpr::Add, ctx.create(BvExpr::Not, _x), _x));
  candidates.push_back(ctx.create(BvExpr::Add, ctx.create(BvExpr::Not, _x), _c0));
  candidates.push_back(ctx.create(BvExpr::Add, ctx.create(BvExpr::Add, _x, _x), _x));
  candidates.push_back(ctx.create(BvExpr::Add, ctx.create(BvExpr::Add, _x, _x), _c0));
  candidates.push_back(ctx.create(BvExpr::Add, ctx.create(BvExpr::Sub, _x, _c0), _x));
  candidates.push_back(ctx.create(BvExpr::Add, ctx.create(BvExpr::Sub, _x, _c0), _c1));
  candidates.push_back(ctx.create(BvExpr::Add, ctx.create(BvExpr::Sub, _c0, _x), _x));
  candidates.push_back(ctx.create(BvExpr::Add, ctx.create(BvExpr::Sub, _c0, _x), _c1));
  candidates.push_back(ctx.create(BvExpr::Add, ctx.create(BvExpr::Mul, _x, _x), _x));
  candidates.push_back(ctx.create(BvExpr::Add, ctx.create(BvExpr::Mul, _x, _x), _c0));
  candidates.push_back(ctx.create(BvExpr::Add, ctx.create(BvExpr::Div, _x, _c0), _x));
  candidates.push_back(ctx.create(BvExpr::Add, ctx.create(BvExpr::Div, _x, _c0), _c1));
  candidates.push_back(ctx.create(BvExpr::Add, ctx.create(BvExpr::Div, _c0, _x), _x));
  candidates.push_back(ctx.create(BvExpr::Add, ctx.create(BvExpr::Div, _c0, _x), _c1));
  candidates.push_back(ctx.create(BvExpr::Add, ctx.create(BvExpr::Mod, _x, _c0), _x));
  candidates.push_back(ctx.create(BvExpr::Add, ctx.create(BvExpr::Mod, _x, _c0), _c1));
  candidates.push_back(ctx.create(BvExpr::Add, ctx.create(BvExpr::Mod, _c0, _x), _x));
  candidates.push_back(ctx.create(BvExpr::Add, ctx.create(BvExpr::Mod, _c0, _x), _c1));
  candidates.push_back(ctx.create(BvExpr::Add, ctx.create(BvExpr::MulMod, _x, _x, _c0), _x));
  candidates.push_back(ctx.create(BvExpr::Add, ctx.create(BvExpr::MulMod, _x, _x, _c0), _c1));
  candidates.push_back(ctx.create(BvExpr::Add, ctx.create(BvExpr::Ite, _x, _x, _c0), _x));
  candidates.push_back(ctx.create(BvExpr::Add, ctx.create(BvExpr::Ite, _x, _x, _c0), _c1));
  candidates.push_back(ctx.create(BvExpr::Add, ctx.create(BvExpr::Ite, _x, _c0, _x), _x));
  candidates.push_back(ctx.create(BvExpr::Add, ctx.create(BvExpr::Ite, _x, _c0, _x), _c1));
  candidates.push_back(ctx.create(BvExpr::Add, _x, ctx.create(BvExpr::Minus, _x)));
  candidates.push_back(ctx.create(BvExpr::Add, _x, ctx.create(BvExpr::Not, _x)));
  candidates.push_back(ctx.create(BvExpr::Add, _x, ctx.create(BvExpr::Add, _x, _x)));
  candidates.push_back(ctx.create(BvExpr::Add, _x, ctx.create(BvExpr::Sub, _x, _c0)));
  candidates.push_back(ctx.create(BvExpr::Add, _x, ctx.create(BvExpr::Sub, _c0, _x)));
  candidates.push_back(ctx.create(BvExpr::Add, _x, ctx.create(BvExpr::Mul, _x, _x)));
  candidates.push_back(ctx.create(BvExpr::Add, _x, ctx.create(BvExpr::Div, _x, _c0)));
  candidates.push_back(ctx.create(BvExpr::Add, _x, ctx.create(BvExpr::Div, _c0, _x)));
  candidates.push_back(ctx.create(BvExpr::Add, _x, ctx.create(BvExpr::Mod, _x, _c0)));
  candidates.push_back(ctx.create(BvExpr::Add, _x, ctx.create(BvExpr::Mod, _c0, _x)));
  candidates.push_back(ctx.create(BvExpr::Add, _x, ctx.create(BvExpr::MulMod, _x, _x, _c0)));
  candidates.push_back(ctx.create(BvExpr::Add, _x, ctx.create(BvExpr::Ite, _x, _x, _c0)));
  candidates.push_back(ctx.create(BvExpr::Add, _x, ctx.create(BvExpr::Ite, _x, _c0, _x)));
  candidates.push_back(ctx.create(BvExpr::Add, _c0, ctx.create(BvExpr::Minus, _x)));
  candidates.push_back(ctx.create(BvExpr::Add, _c0, ctx.create(BvExpr::Not, _x)));
  candidates.push_back(ctx.create(BvExpr::Add, _c0, ctx.create(BvExpr::Add, _x, _x)));
  candidates.push_back(ctx.create(BvExpr::Add, _c0, ctx.create(BvExpr::Sub, _x, _c1)));
  candidates.push_back(ctx.create(BvExpr::Add, _c0, ctx.create(BvExpr::Sub, _c1, _x)));
  candidates.push_back(ctx.create(BvExpr::Add, _c0, ctx.create(BvExpr::Mul, _x, _x)));
  candidates.push_back(ctx.create(BvExpr::Add, _c0, ctx.create(BvExpr::Div, _x, _c1)));
  candidates.push_back(ctx.create(BvExpr::Add, _c0, ctx.create(BvExpr::Div, _c1, _x)));
  candidates.push_back(ctx.create(BvExpr::Add, _c0, ctx.create(BvExpr::Mod, _x, _c1)));
  candidates.push_back(ctx.create(BvExpr::Add, _c0, ctx.create(BvExpr::Mod, _c1, _x)));
  candidates.push_back(ctx.create(BvExpr::Add, _c0, ctx.create(BvExpr::MulMod, _x, _x, _c1)));
  candidates.push_back(ctx.create(BvExpr::Add, _c0, ctx.create(BvExpr::Ite, _x, _x, _c1)));
  candidates.push_back(ctx.create(BvExpr::Add, _c0, ctx.create(BvExpr::Ite, _x, _c1, _x)));
  candidates.push_back(ctx.create(BvExpr::Sub, ctx.create(BvExpr::Minus, _x), _x));
  candidates.push_back(ctx.create(BvExpr::Sub, ctx.create(BvExpr::Minus, _x), _c0));
  candidates.push_back(ctx.create(BvExpr::Sub, ctx.create(BvExpr::Not, _x), _x));
  candidates.push_back(ctx.create(BvExpr::Sub, ctx.create(BvExpr::Not, _x), _c0));
  candidates.push_back(ctx.create(BvExpr::Sub, ctx.create(BvExpr::Add, _x, _x), _x));
  candidates.push_back(ctx.create(BvExpr::Sub, ctx.create(BvExpr::Add, _x, _x), _c0));
  candidates.push_back(ctx.create(BvExpr::Sub, ctx.create(BvExpr::Sub, _x, _c0), _x));
  candidates.push_back(ctx.create(BvExpr::Sub, ctx.create(BvExpr::Sub, _x, _c0), _c1));
  candidates.push_back(ctx.create(BvExpr::Sub, ctx.create(BvExpr::Sub, _c0, _x), _x));
  candidates.push_back(ctx.create(BvExpr::Sub, ctx.create(BvExpr::Sub, _c0, _x), _c1));
  candidates.push_back(ctx.create(BvExpr::Sub, ctx.create(BvExpr::Mul, _x, _x), _x));
  candidates.push_back(ctx.create(BvExpr::Sub, ctx.create(BvExpr::Mul, _x, _x), _c0));
  candidates.push_back(ctx.create(BvExpr::Sub, ctx.create(BvExpr::Div, _x, _c0), _x));
  candidates.push_back(ctx.create(BvExpr::Sub, ctx.create(BvExpr::Div, _x, _c0), _c1));
  candidates.push_back(ctx.create(BvExpr::Sub, ctx.create(BvExpr::Div, _c0, _x), _x));
  candidates.push_back(ctx.create(BvExpr::Sub, ctx.create(BvExpr::Div, _c0, _x), _c1));
  candidates.push_back(ctx.create(BvExpr::Sub, ctx.create(BvExpr::Mod, _x, _c0), _x));
  candidates.push_back(ctx.create(BvExpr::Sub, ctx.create(BvExpr::Mod, _x, _c0), _c1));
  candidates.push_back(ctx.create(BvExpr::Sub, ctx.create(BvExpr::Mod, _c0, _x), _x));
  candidates.push_back(ctx.create(BvExpr::Sub, ctx.create(BvExpr::Mod, _c0, _x), _c1));
  candidates.push_back(ctx.create(BvExpr::Sub, ctx.create(BvExpr::MulMod, _x, _x, _c0), _x));
  candidates.push_back(ctx.create(BvExpr::Sub, ctx.create(BvExpr::MulMod, _x, _x, _c0), _c1));
  candidates.push_back(ctx.create(BvExpr::Sub, ctx.create(BvExpr::Ite, _x, _x, _c0), _x));
  candidates.push_back(ctx.create(BvExpr::Sub, ctx.create(BvExpr::Ite, _x, _x, _c0), _c1));
  candidates.push_back(ctx.create(BvExpr::Sub, ctx.create(BvExpr::Ite, _x, _c0, _x), _x));
  candidates.push_back(ctx.create(BvExpr::Sub, ctx.create(BvExpr::Ite, _x, _c0, _x), _c1));
  candidates.push_back(ctx.create(BvExpr::Sub, _x, ctx.create(BvExpr::Minus, _x)));
  candidates.push_back(ctx.create(BvExpr::Sub, _x, ctx.create(BvExpr::Not, _x)));
  candidates.push_back(ctx.create(BvExpr::Sub, _x, ctx.create(BvExpr::Add, _x, _x)));
  candidates.push_back(ctx.create(BvExpr::Sub, _x, ctx.create(BvExpr::Sub, _x, _c0)));
  candidates.push_back(ctx.create(BvExpr::Sub, _x, ctx.create(BvExpr::Sub, _c0, _x)));
  candidates.push_back(ctx.create(BvExpr::Sub, _x, ctx.create(BvExpr::Mul, _x, _x)));
  candidates.push_back(ctx.create(BvExpr::Sub, _x, ctx.create(BvExpr::Div, _x, _c0)));
  candidates.push_back(ctx.create(BvExpr::Sub, _x, ctx.create(BvExpr::Div, _c0, _x)));
  candidates.push_back(ctx.create(BvExpr::Sub, _x, ctx.create(BvExpr::Mod, _x, _c0)));
  candidates.push_back(ctx.create(BvExpr::Sub, _x, ctx.create(BvExpr::Mod, _c0, _x)));
  candidates.push_back(ctx.create(BvExpr::Sub, _x, ctx.create(BvExpr::MulMod, _x, _x, _c0)));
  candidates.push_back(ctx.create(BvExpr::Sub, _x, ctx.create(BvExpr::Ite, _x, _x, _c0)));
  candidates.push_back(ctx.create(BvExpr::Sub, _x, ctx.create(BvExpr::Ite, _x, _c0, _x)));
  candidates.push_back(ctx.create(BvExpr::Sub, _c0, ctx.create(BvExpr::Minus, _x)));
  candidates.push_back(ctx.create(BvExpr::Sub, _c0, ctx.create(BvExpr::Not, _x)));
  candidates.push_back(ctx.create(BvExpr::Sub, _c0, ctx.create(BvExpr::Add, _x, _x)));
  candidates.push_back(ctx.create(BvExpr::Sub, _c0, ctx.create(BvExpr::Sub, _x, _c1)));
  candidates.push_back(ctx.create(BvExpr::Sub, _c0, ctx.create(BvExpr::Sub, _c1, _x)));
  candidates.push_back(ctx.create(BvExpr::Sub, _c0, ctx.create(BvExpr::Mul, _x, _x)));
  candidates.push_back(ctx.create(BvExpr::Sub, _c0, ctx.create(BvExpr::Div, _x, _c1)));
  candidates.push_back(ctx.create(BvExpr::Sub, _c0, ctx.create(BvExpr::Div, _c1, _x)));
  candidates.push_back(ctx.create(BvExpr::Sub, _c0, ctx.create(BvExpr::Mod, _x, _c1)));
  candidates.push_back(ctx.create(BvExpr::Sub, _c0, ctx.create(BvExpr::Mod, _c1, _x)));
  candidates.push_back(ctx.create(BvExpr::Sub, _c0, ctx.create(BvExpr::MulMod, _x, _x, _c1)));
  candidates.push_back(ctx.create(BvExpr::Sub, _c0, ctx.create(BvExpr::Ite, _x, _x, _c1)));
  candidates.push_back(ctx.create(BvExpr::Sub, _c0, ctx.create(BvExpr::Ite, _x, _c1, _x)));
  candidates.push_back(ctx.create(BvExpr::And, ctx.create(BvExpr::Minus, _x), _x));
  candidates.push_back(ctx.create(BvExpr::And, ctx.create(BvExpr::Minus, _x), _c0));
  candidates.push_back(ctx.create(BvExpr::And, ctx.create(BvExpr::Not, _x), _x));
  candidates.push_back(ctx.create(BvExpr::And, ctx.create(BvExpr::Not, _x), _c0));
  candidates.push_back(ctx.create(BvExpr::And, ctx.create(BvExpr::Add, _x, _x), _x));
  candidates.push_back(ctx.create(BvExpr::And, ctx.create(BvExpr::Add, _x, _x), _c0));
  candidates.push_back(ctx.create(BvExpr::And, ctx.create(BvExpr::Sub, _x, _c0), _x));
  candidates.push_back(ctx.create(BvExpr::And, ctx.create(BvExpr::Sub, _x, _c0), _c1));
  candidates.push_back(ctx.create(BvExpr::And, ctx.create(BvExpr::Sub, _c0, _x), _x));
  candidates.push_back(ctx.create(BvExpr::And, ctx.create(BvExpr::Sub, _c0, _x), _c1));
  candidates.push_back(ctx.create(BvExpr::And, ctx.create(BvExpr::Mul, _x, _x), _x));
  candidates.push_back(ctx.create(BvExpr::And, ctx.create(BvExpr::Mul, _x, _x), _c0));
  candidates.push_back(ctx.create(BvExpr::And, ctx.create(BvExpr::Div, _x, _c0), _x));
  candidates.push_back(ctx.create(BvExpr::And, ctx.create(BvExpr::Div, _x, _c0), _c1));
  candidates.push_back(ctx.create(BvExpr::And, ctx.create(BvExpr::Div, _c0, _x), _x));
  candidates.push_back(ctx.create(BvExpr::And, ctx.create(BvExpr::Div, _c0, _x), _c1));
  candidates.push_back(ctx.create(BvExpr::And, ctx.create(BvExpr::Mod, _x, _c0), _x));
  candidates.push_back(ctx.create(BvExpr::And, ctx.create(BvExpr::Mod, _x, _c0), _c1));
  candidates.push_back(ctx.create(BvExpr::And, ctx.create(BvExpr::Mod, _c0, _x), _x));
  candidates.push_back(ctx.create(BvExpr::And, ctx.create(BvExpr::Mod, _c0, _x), _c1));
  candidates.push_back(ctx.create(BvExpr::And, ctx.create(BvExpr::MulMod, _x, _x, _c0), _x));
  candidates.push_back(ctx.create(BvExpr::And, ctx.create(BvExpr::MulMod, _x, _x, _c0), _c1));
  candidates.push_back(ctx.create(BvExpr::And, ctx.create(BvExpr::Ite, _x, _x, _c0), _x));
  candidates.push_back(ctx.create(BvExpr::And, ctx.create(BvExpr::Ite, _x, _x, _c0), _c1));
  candidates.push_back(ctx.create(BvExpr::And, ctx.create(BvExpr::Ite, _x, _c0, _x), _x));
  candidates.push_back(ctx.create(BvExpr::And, ctx.create(BvExpr::Ite, _x, _c0, _x), _c1));
  candidates.push_back(ctx.create(BvExpr::And, _x, ctx.create(BvExpr::Minus, _x)));
  candidates.push_back(ctx.create(BvExpr::And, _x, ctx.create(BvExpr::Not, _x)));
  candidates.push_back(ctx.create(BvExpr::And, _x, ctx.create(BvExpr::Add, _x, _x)));
  candidates.push_back(ctx.create(BvExpr::And, _x, ctx.create(BvExpr::Sub, _x, _c0)));
  candidates.push_back(ctx.create(BvExpr::And, _x, ctx.create(BvExpr::Sub, _c0, _x)));
  candidates.push_back(ctx.create(BvExpr::And, _x, ctx.create(BvExpr::Mul, _x, _x)));
  candidates.push_back(ctx.create(BvExpr::And, _x, ctx.create(BvExpr::Div, _x, _c0)));
  candidates.push_back(ctx.create(BvExpr::And, _x, ctx.create(BvExpr::Div, _c0, _x)));
  candidates.push_back(ctx.create(BvExpr::And, _x, ctx.create(BvExpr::Mod, _x, _c0)));
  candidates.push_back(ctx.create(BvExpr::And, _x, ctx.create(BvExpr::Mod, _c0, _x)));
  candidates.push_back(ctx.create(BvExpr::And, _x, ctx.create(BvExpr::MulMod, _x, _x, _c0)));
  candidates.push_back(ctx.create(BvExpr::And, _x, ctx.create(BvExpr::Ite, _x, _x, _c0)));
  candidates.push_back(ctx.create(BvExpr::And, _x, ctx.create(BvExpr::Ite, _x, _c0, _x)));
  candidates.push_back(ctx.create(BvExpr::And, _c0, ctx.create(BvExpr::Minus, _x)));
  candidates.push_back(ctx.create(BvExpr::And, _c0, ctx.create(BvExpr::Not, _x)));
  candidates.push_back(ctx.create(BvExpr::And, _c0, ctx.create(BvExpr::Add, _x, _x)));
  candidates.push_back(ctx.create(BvExpr::And, _c0, ctx.create(BvExpr::Sub, _x, _c1)));
  candidates.push_back(ctx.create(BvExpr::And, _c0, ctx.create(BvExpr::Sub, _c1, _x)));
  candidates.push_back(ctx.create(BvExpr::And, _c0, ctx.create(BvExpr::Mul, _x, _x)));
  candidates.push_back(ctx.create(BvExpr::And, _c0, ctx.create(BvExpr::Div, _x, _c1)));
  candidates.push_back(ctx.create(BvExpr::And, _c0, ctx.create(BvExpr::Div, _c1, _x)));
  candidates.push_back(ctx.create(BvExpr::And, _c0, ctx.create(BvExpr::Mod, _x, _c1)));
  candidates.push_back(ctx.create(BvExpr::And, _c0, ctx.create(BvExpr::Mod, _c1, _x)));
  candidates.push_back(ctx.create(BvExpr::And, _c0, ctx.create(BvExpr::MulMod, _x, _x, _c1)));
  candidates.push_back(ctx.create(BvExpr::And, _c0, ctx.create(BvExpr::Ite, _x, _x, _c1)));
  candidates.push_back(ctx.create(BvExpr::And, _c0, ctx.create(BvExpr::Ite, _x, _c1, _x)));
  candidates.push_back(ctx.create(BvExpr::Or, ctx.create(BvExpr::Minus, _x), _x));
  candidates.push_back(ctx.create(BvExpr::Or, ctx.create(BvExpr::Minus, _x), _c0));
  candidates.push_back(ctx.create(BvExpr::Or, ctx.create(BvExpr::Not, _x), _x));
  candidates.push_back(ctx.create(BvExpr::Or, ctx.create(BvExpr::Not, _x), _c0));
  candidates.push_back(ctx.create(BvExpr::Or, ctx.create(BvExpr::Add, _x, _x), _x));
  candidates.push_back(ctx.create(BvExpr::Or, ctx.create(BvExpr::Add, _x, _x), _c0));
  candidates.push_back(ctx.create(BvExpr::Or, ctx.create(BvExpr::Sub, _x, _c0), _x));
  candidates.push_back(ctx.create(BvExpr::Or, ctx.create(BvExpr::Sub, _x, _c0), _c1));
  candidates.push_back(ctx.create(BvExpr::Or, ctx.create(BvExpr::Sub, _c0, _x), _x));
  candidates.push_back(ctx.create(BvExpr::Or, ctx.create(BvExpr::Sub, _c0, _x), _c1));
  candidates.push_back(ctx.create(BvExpr::Or, ctx.create(BvExpr::Mul, _x, _x), _x));
  candidates.push_back(ctx.create(BvExpr::Or, ctx.create(BvExpr::Mul, _x, _x), _c0));
  candidates.push_back(ctx.create(BvExpr::Or, ctx.create(BvExpr::Div, _x, _c0), _x));
  candidates.push_back(ctx.create(BvExpr::Or, ctx.create(BvExpr::Div, _x, _c0), _c1));
  candidates.push_back(ctx.create(BvExpr::Or, ctx.create(BvExpr::Div, _c0, _x), _x));
  candidates.push_back(ctx.create(BvExpr::Or, ctx.create(BvExpr::Div, _c0, _x), _c1));
  candidates.push_back(ctx.create(BvExpr::Or, ctx.create(BvExpr::Mod, _x, _c0), _x));
  candidates.push_back(ctx.create(BvExpr::Or, ctx.create(BvExpr::Mod, _x, _c0), _c1));
  candidates.push_back(ctx.create(BvExpr::Or, ctx.create(BvExpr::Mod, _c0, _x), _x));
  candidates.push_back(ctx.create(BvExpr::Or, ctx.create(BvExpr::Mod, _c0, _x), _c1));
  candidates.push_back(ctx.create(BvExpr::Or, ctx.create(BvExpr::MulMod, _x, _x, _c0), _x));
  candidates.push_back(ctx.create(BvExpr::Or, ctx.create(BvExpr::MulMod, _x, _x, _c0), _c1));
  candidates.push_back(ctx.create(BvExpr::Or, ctx.create(BvExpr::Ite, _x, _x, _c0), _x));
  candidates.push_back(ctx.create(BvExpr::Or, ctx.create(BvExpr::Ite, _x, _x, _c0), _c1));
  candidates.push_back(ctx.create(BvExpr::Or, ctx.create(BvExpr::Ite, _x, _c0, _x), _x));
  candidates.push_back(ctx.create(BvExpr::Or, ctx.create(BvExpr::Ite, _x, _c0, _x), _c1));
  candidates.push_back(ctx.create(BvExpr::Or, _x, ctx.create(BvExpr::Minus, _x)));
  candidates.push_back(ctx.create(BvExpr::Or, _x, ctx.create(BvExpr::Not, _x)));
  candidates.push_back(ctx.create(BvExpr::Or, _x, ctx.create(BvExpr::Add, _x, _x)));
  candidates.push_back(ctx.create(BvExpr::Or, _x, ctx.create(BvExpr::Sub, _x, _c0)));
  candidates.push_back(ctx.create(BvExpr::Or, _x, ctx.create(BvExpr::Sub, _c0, _x)));
  candidates.push_back(ctx.create(BvExpr::Or, _x, ctx.create(BvExpr::Mul, _x, _x)));
  candidates.push_back(ctx.create(BvExpr::Or, _x, ctx.create(BvExpr::Div, _x, _c0)));
  candidates.push_back(ctx.create(BvExpr::Or, _x, ctx.create(BvExpr::Div, _c0, _x)));
  candidates.push_back(ctx.create(BvExpr::Or, _x, ctx.create(BvExpr::Mod, _x, _c0)));
  candidates.push_back(ctx.create(BvExpr::Or, _x, ctx.create(BvExpr::Mod, _c0, _x)));
  candidates.push_back(ctx.create(BvExpr::Or, _x, ctx.create(BvExpr::MulMod, _x, _x, _c0)));
  candidates.push_back(ctx.create(BvExpr::Or, _x, ctx.create(BvExpr::Ite, _x, _x, _c0)));
  candidates.push_back(ctx.create(BvExpr::Or, _x, ctx.create(BvExpr::Ite, _x, _c0, _x)));
  candidates.push_back(ctx.create(BvExpr::Or, _c0, ctx.create(BvExpr::Minus, _x)));
  candidates.push_back(ctx.create(BvExpr::Or, _c0, ctx.create(BvExpr::Not, _x)));
  candidates.push_back(ctx.create(BvExpr::Or, _c0, ctx.create(BvExpr::Add, _x, _x)));
  candidates.push_back(ctx.create(BvExpr::Or, _c0, ctx.create(BvExpr::Sub, _x, _c1)));
  candidates.push_back(ctx.create(BvExpr::Or, _c0, ctx.create(BvExpr::Sub, _c1, _x)));
  candidates.push_back(ctx.create(BvExpr::Or, _c0, ctx.create(BvExpr::Mul, _x, _x)));
  candidates.push_back(ctx.create(BvExpr::Or, _c0, ctx.create(BvExpr::Div, _x, _c1)));
  candidates.push_back(ctx.create(BvExpr::Or, _c0, ctx.create(BvExpr::Div, _c1, _x)));
  candidates.push_back(ctx.create(BvExpr::Or, _c0, ctx.create(BvExpr::Mod, _x, _c1)));
  candidates.push_back(ctx.create(BvExpr::Or, _c0, ctx.create(BvExpr::Mod, _c1, _x)));
  candidates.push_back(ctx.create(BvExpr::Or, _c0, ctx.create(BvExpr::MulMod, _x, _x, _c1)));
  candidates.push_back(ctx.create(BvExpr::Or, _c0, ctx.create(BvExpr::Ite, _x, _x, _c1)));
  candidates.push_back(ctx.create(BvExpr::Or, _c0, ctx.create(BvExpr::Ite, _x, _c1, _x)));
  candidates.push_back(ctx.create(BvExpr::Xor, ctx.create(BvExpr::Minus, _x), _x));
  candidates.push_back(ctx.create(BvExpr::Xor, ctx.create(BvExpr::Minus, _x), _c0));
  candidates.push_back(ctx.create(BvExpr::Xor, ctx.create(BvExpr::Not, _x), _x));
  candidates.push_back(ctx.create(BvExpr::Xor, ctx.create(BvExpr::Not, _x), _c0));
  candidates.push_back(ctx.create(BvExpr::Xor, ctx.create(BvExpr::Add, _x, _x), _x));
  candidates.push_back(ctx.create(BvExpr::Xor, ctx.create(BvExpr::Add, _x, _x), _c0));
  candidates.push_back(ctx.create(BvExpr::Xor, ctx.create(BvExpr::Sub, _x, _c0), _x));
  candidates.push_back(ctx.create(BvExpr::Xor, ctx.create(BvExpr::Sub, _x, _c0), _c1));
  candidates.push_back(ctx.create(BvExpr::Xor, ctx.create(BvExpr::Sub, _c0, _x), _x));
  candidates.push_back(ctx.create(BvExpr::Xor, ctx.create(BvExpr::Sub, _c0, _x), _c1));
  candidates.push_back(ctx.create(BvExpr::Xor, ctx.create(BvExpr::Mul, _x, _x), _x));
  candidates.push_back(ctx.create(BvExpr::Xor, ctx.create(BvExpr::Mul, _x, _x), _c0));
  candidates.push_back(ctx.create(BvExpr::Xor, ctx.create(BvExpr::Div, _x, _c0), _x));
  candidates.push_back(ctx.create(BvExpr::Xor, ctx.create(BvExpr::Div, _x, _c0), _c1));
  candidates.push_back(ctx.create(BvExpr::Xor, ctx.create(BvExpr::Div, _c0, _x), _x));
  candidates.push_back(ctx.create(BvExpr::Xor, ctx.create(BvExpr::Div, _c0, _x), _c1));
  candidates.push_back(ctx.create(BvExpr::Xor, ctx.create(BvExpr::Mod, _x, _c0), _x));
  candidates.push_back(ctx.create(BvExpr::Xor, ctx.create(BvExpr::Mod, _x, _c0), _c1));
  candidates.push_back(ctx.create(BvExpr::Xor, ctx.create(BvExpr::Mod, _c0, _x), _x));
  candidates.push_back(ctx.create(BvExpr::Xor, ctx.create(BvExpr::Mod, _c0, _x), _c1));
  candidates.push_back(ctx.create(BvExpr::Xor, ctx.create(BvExpr::MulMod, _x, _x, _c0), _x));
  candidates.push_back(ctx.create(BvExpr::Xor, ctx.create(BvExpr::MulMod, _x, _x, _c0), _c1));
  candidates.push_back(ctx.create(BvExpr::Xor, ctx.create(BvExpr::Ite, _x, _x, _c0), _x));
  candidates.push_back(ctx.create(BvExpr::Xor, ctx.create(BvExpr::Ite, _x, _x, _c0), _c1));
  candidates.push_back(ctx.create(BvExpr::Xor, ctx.create(BvExpr::Ite, _x, _c0, _x), _x));
  candidates.push_back(ctx.create(BvExpr::Xor, ctx.create(BvExpr::Ite, _x, _c0, _x), _c1));
  candidates.push_back(ctx.create(BvExpr::Xor, _x, ctx.create(BvExpr::Minus, _x)));
  candidates.push_back(ctx.create(BvExpr::Xor, _x, ctx.create(BvExpr::Not, _x)));
  candidates.push_back(ctx.create(BvExpr::Xor, _x, ctx.create(BvExpr::Add, _x, _x)));
  candidates.push_back(ctx.create(BvExpr::Xor, _x, ctx.create(BvExpr::Sub, _x, _c0)));
  candidates.push_back(ctx.create(BvExpr::Xor, _x, ctx.create(BvExpr::Sub, _c0, _x)));
  candidates.push_back(ctx.create(BvExpr::Xor, _x, ctx.create(BvExpr::Mul, _x, _x)));
  candidates.push_back(ctx.create(BvExpr::Xor, _x, ctx.create(BvExpr::Div, _x, _c0)));
  candidates.push_back(ctx.create(BvExpr::Xor, _x, ctx.create(BvExpr::Div, _c0, _x)));
  candidates.push_back(ctx.create(BvExpr::Xor, _x, ctx.create(BvExpr::Mod, _x, _c0)));
  candidates.push_back(ctx.create(BvExpr::Xor, _x, ctx.create(BvExpr::Mod, _c0, _x)));
  candidates.push_back(ctx.create(BvExpr::Xor, _x, ctx.create(BvExpr::MulMod, _x, _x, _c0)));
  candidates.push_back(ctx.create(BvExpr::Xor, _x, ctx.create(BvExpr::Ite, _x, _x, _c0)));
  candidates.push_back(ctx.create(BvExpr::Xor, _x, ctx.create(BvExpr::Ite, _x, _c0, _x)));
  candidates.push_back(ctx.create(BvExpr::Xor, _c0, ctx.create(BvExpr::Minus, _x)));
  candidates.push_back(ctx.create(BvExpr::Xor, _c0, ctx.create(BvExpr::Not, _x)));
  candidates.push_back(ctx.create(BvExpr::Xor, _c0, ctx.create(BvExpr::Add, _x, _x)));
  candidates.push_back(ctx.create(BvExpr::Xor, _c0, ctx.create(BvExpr::Sub, _x, _c1)));
  candidates.push_back(ctx.create(BvExpr::Xor, _c0, ctx.create(BvExpr::Sub, _c1, _x)));
  candidates.push_back(ctx.create(BvExpr::Xor, _c0, ctx.create(BvExpr::Mul, _x, _x)));
  candidates.push_back(ctx.create(BvExpr::Xor, _c0, ctx.create(BvExpr::Div, _x, _c1)));
  candidates.push_back(ctx.create(BvExpr::Xor, _c0, ctx.create(BvExpr::Div, _c1, _x)));
  candidates.push_back(ctx.create(BvExpr::Xor, _c0, ctx.create(BvExpr::Mod, _x, _c1)));
  candidates.push_back(ctx.create(BvExpr::Xor, _c0, ctx.create(BvExpr::Mod, _c1, _x)));
  candidates.push_back(ctx.create(BvExpr::Xor, _c0, ctx.create(BvExpr::MulMod, _x, _x, _c1)));
  candidates.push_back(ctx.create(BvExpr::Xor, _c0, ctx.create(BvExpr::Ite, _x, _x, _c1)));
  candidates.push_back(ctx.create(BvExpr::Xor, _c0, ctx.create(BvExpr::Ite, _x, _c1, _x)));
  candidates.push_back(ctx.create(BvExpr::Mul, ctx.create(BvExpr::Minus, _x), _x));
  candidates.push_back(ctx.create(BvExpr::Mul, ctx.create(BvExpr::Minus, _x), _c0));
  candidates.push_back(ctx.create(BvExpr::Mul, ctx.create(BvExpr::Not, _x), _x));
  candidates.push_back(ctx.create(BvExpr::Mul, ctx.create(BvExpr::Not, _x), _c0));
  candidates.push_back(ctx.create(BvExpr::Mul, ctx.create(BvExpr::Add, _x, _x), _x));
  candidates.push_back(ctx.create(BvExpr::Mul, ctx.create(BvExpr::Add, _x, _x), _c0));
  candidates.push_back(ctx.create(BvExpr::Mul, ctx.create(BvExpr::Sub, _x, _c0), _x));
  candidates.push_back(ctx.create(BvExpr::Mul, ctx.create(BvExpr::Sub, _x, _c0), _c1));
  candidates.push_back(ctx.create(BvExpr::Mul, ctx.create(BvExpr::Sub, _c0, _x), _x));
  candidates.push_back(ctx.create(BvExpr::Mul, ctx.create(BvExpr::Sub, _c0, _x), _c1));
  candidates.push_back(ctx.create(BvExpr::Mul, ctx.create(BvExpr::Mul, _x, _x), _x));
  candidates.push_back(ctx.create(BvExpr::Mul, ctx.create(BvExpr::Mul, _x, _x), _c0));
  candidates.push_back(ctx.create(BvExpr::Mul, ctx.create(BvExpr::Div, _x, _c0), _x));
  candidates.push_back(ctx.create(BvExpr::Mul, ctx.create(BvExpr::Div, _x, _c0), _c1));
  candidates.push_back(ctx.create(BvExpr::Mul, ctx.create(BvExpr::Div, _c0, _x), _x));
  candidates.push_back(ctx.create(BvExpr::Mul, ctx.create(BvExpr::Div, _c0, _x), _c1));
  candidates.push_back(ctx.create(BvExpr::Mul, ctx.create(BvExpr::Mod, _x, _c0), _x));
  candidates.push_back(ctx.create(BvExpr::Mul, ctx.create(BvExpr::Mod, _x, _c0), _c1));
  candidates.push_back(ctx.create(BvExpr::Mul, ctx.create(BvExpr::Mod, _c0, _x), _x));
  candidates.push_back(ctx.create(BvExpr::Mul, ctx.create(BvExpr::Mod, _c0, _x), _c1));
  candidates.push_back(ctx.create(BvExpr::Mul, ctx.create(BvExpr::MulMod, _x, _x, _c0), _x));
  candidates.push_back(ctx.create(BvExpr::Mul, ctx.create(BvExpr::MulMod, _x, _x, _c0), _c1));
  candidates.push_back(ctx.create(BvExpr::Mul, ctx.create(BvExpr::Ite, _x, _x, _c0), _x));
  candidates.push_back(ctx.create(BvExpr::Mul, ctx.create(BvExpr::Ite, _x, _x, _c0), _c1));
  candidates.push_back(ctx.create(BvExpr::Mul, ctx.create(BvExpr::Ite, _x, _c0, _x), _x));
  candidates.push_back(ctx.create(BvExpr::Mul, ctx.create(BvExpr::Ite, _x, _c0, _x), _c1));
  candidates.push_back(ctx.create(BvExpr::Mul, _x, ctx.create(BvExpr::Minus, _x)));
  candidates.push_back(ctx.create(BvExpr::Mul, _x, ctx.create(BvExpr::Not, _x)));
  candidates.push_back(ctx.create(BvExpr::Mul, _x, ctx.create(BvExpr::Add, _x, _x)));
  candidates.push_back(ctx.create(BvExpr::Mul, _x, ctx.create(BvExpr::Sub, _x, _c0)));
  candidates.push_back(ctx.create(BvExpr::Mul, _x, ctx.create(BvExpr::Sub, _c0, _x)));
  candidates.push_back(ctx.create(BvExpr::Mul, _x, ctx.create(BvExpr::Mul, _x, _x)));
  candidates.push_back(ctx.create(BvExpr::Mul, _x, ctx.create(BvExpr::Div, _x, _c0)));
  candidates.push_back(ctx.create(BvExpr::Mul, _x, ctx.create(BvExpr::Div, _c0, _x)));
  candidates.push_back(ctx.create(BvExpr::Mul, _x, ctx.create(BvExpr::Mod, _x, _c0)));
  candidates.push_back(ctx.create(BvExpr::Mul, _x, ctx.create(BvExpr::Mod, _c0, _x)));
  candidates.push_back(ctx.create(BvExpr::Mul, _x, ctx.create(BvExpr::MulMod, _x, _x, _c0)));
  candidates.push_back(ctx.create(BvExpr::Mul, _x, ctx.create(BvExpr::Ite, _x, _x, _c0)));
  candidates.push_back(ctx.create(BvExpr::Mul, _x, ctx.create(BvExpr::Ite, _x, _c0, _x)));
  candidates.push_back(ctx.create(BvExpr::Mul, _c0, ctx.create(BvExpr::Minus, _x)));
  candidates.push_back(ctx.create(BvExpr::Mul, _c0, ctx.create(BvExpr::Not, _x)));
  candidates.push_back(ctx.create(BvExpr::Mul, _c0, ctx.create(BvExpr::Add, _x, _x)));
  candidates.push_back(ctx.create(BvExpr::Mul, _c0, ctx.create(BvExpr::Sub, _x, _c1)));
  candidates.push_back(ctx.create(BvExpr::Mul, _c0, ctx.create(BvExpr::Sub, _c1, _x)));
  candidates.push_back(ctx.create(BvExpr::Mul, _c0, ctx.create(BvExpr::Mul, _x, _x)));
  candidates.push_back(ctx.create(BvExpr::Mul, _c0, ctx.create(BvExpr::Div, _x, _c1)));
  candidates.push_back(ctx.create(BvExpr::Mul, _c0, ctx.create(BvExpr::Div, _c1, _x)));
  candidates.push_back(ctx.create(BvExpr::Mul, _c0, ctx.create(BvExpr::Mod, _x, _c1)));
  candidates.push_back(ctx.create(BvExpr::Mul, _c0, ctx.create(BvExpr::Mod, _c1, _x)));
  candidates.push_back(ctx.create(BvExpr::Mul, _c0, ctx.create(BvExpr::MulMod, _x, _x, _c1)));
  candidates.push_back(ctx.create(BvExpr::Mul, _c0, ctx.create(BvExpr::Ite, _x, _x, _c1)));
  candidates.push_back(ctx.create(BvExpr::Mul, _c0, ctx.create(BvExpr::Ite, _x, _c1, _x)));
  candidates.push_back(ctx.create(BvExpr::Div, ctx.create(BvExpr::Minus, _x), _x));
  candidates.push_back(ctx.create(BvExpr::Div, ctx.create(BvExpr::Minus, _x), _c0));
  candidates.push_back(ctx.create(BvExpr::Div, ctx.create(BvExpr::Not, _x), _x));
  candidates.push_back(ctx.create(BvExpr::Div, ctx.create(BvExpr::Not, _x), _c0));
  candidates.push_back(ctx.create(BvExpr::Div, ctx.create(BvExpr::Add, _x, _x), _x));
  candidates.push_back(ctx.create(BvExpr::Div, ctx.create(BvExpr::Add, _x, _x), _c0));
  candidates.push_back(ctx.create(BvExpr::Div, ctx.create(BvExpr::Sub, _x, _c0), _x));
  candidates.push_back(ctx.create(BvExpr::Div, ctx.create(BvExpr::Sub, _x, _c0), _c1));
  candidates.push_back(ctx.create(BvExpr::Div, ctx.create(BvExpr::Sub, _c0, _x), _x));
  candidates.push_back(ctx.create(BvExpr::Div, ctx.create(BvExpr::Sub, _c0, _x), _c1));
  candidates.push_back(ctx.create(BvExpr::Div, ctx.create(BvExpr::Mul, _x, _x), _x));
  candidates.push_back(ctx.create(BvExpr::Div, ctx.create(BvExpr::Mul, _x, _x), _c0));
  candidates.push_back(ctx.create(BvExpr::Div, ctx.create(BvExpr::Div, _x, _c0), _x));
  candidates.push_back(ctx.create(BvExpr::Div, ctx.create(BvExpr::Div, _x, _c0), _c1));
  candidates.push_back(ctx.create(BvExpr::Div, ctx.create(BvExpr::Div, _c0, _x), _x));
  candidates.push_back(ctx.create(BvExpr::Div, ctx.create(BvExpr::Div, _c0, _x), _c1));
  candidates.push_back(ctx.create(BvExpr::Div, ctx.create(BvExpr::Mod, _x, _c0), _x));
  candidates.push_back(ctx.create(BvExpr::Div, ctx.create(BvExpr::Mod, _x, _c0), _c1));
  candidates.push_back(ctx.create(BvExpr::Div, ctx.create(BvExpr::Mod, _c0, _x), _x));
  candidates.push_back(ctx.create(BvExpr::Div, ctx.create(BvExpr::Mod, _c0, _x), _c1));
  candidates.push_back(ctx.create(BvExpr::Div, ctx.create(BvExpr::MulMod, _x, _x, _c0), _x));
  candidates.push_back(ctx.create(BvExpr::Div, ctx.create(BvExpr::MulMod, _x, _x, _c0), _c1));
  candidates.push_back(ctx.create(BvExpr::Div, ctx.create(BvExpr::Ite, _x, _x, _c0), _x));
  candidates.push_back(ctx.create(BvExpr::Div, ctx.create(BvExpr::Ite, _x, _x, _c0), _c1));
  candidates.push_back(ctx.create(BvExpr::Div, ctx.create(BvExpr::Ite, _x, _c0, _x), _x));
  candidates.push_back(ctx.create(BvExpr::Div, ctx.create(BvExpr::Ite, _x, _c0, _x), _c1));
  candidates.push_back(ctx.create(BvExpr::Div, _x, ctx.create(BvExpr::Minus, _x)));
  candidates.push_back(ctx.create(BvExpr::Div, _x, ctx.create(BvExpr::Not, _x)));
  candidates.push_back(ctx.create(BvExpr::Div, _x, ctx.create(BvExpr::Add, _x, _x)));
  candidates.push_back(ctx.create(BvExpr::Div, _x, ctx.create(BvExpr::Sub, _x, _c0)));
  candidates.push_back(ctx.create(BvExpr::Div, _x, ctx.create(BvExpr::Sub, _c0, _x)));
  candidates.push_back(ctx.create(BvExpr::Div, _x, ctx.create(BvExpr::Mul, _x, _x)));
  candidates.push_back(ctx.create(BvExpr::Div, _x, ctx.create(BvExpr::Div, _x, _c0)));
  candidates.push_back(ctx.create(BvExpr::Div, _x, ctx.create(BvExpr::Div, _c0, _x)));
  candidates.push_back(ctx.create(BvExpr::Div, _x, ctx.create(BvExpr::Mod, _x, _c0)));
  candidates.push_back(ctx.create(BvExpr::Div, _x, ctx.create(BvExpr::Mod, _c0, _x)));
  candidates.push_back(ctx.create(BvExpr::Div, _x, ctx.create(BvExpr::MulMod, _x, _x, _c0)));
  candidates.push_back(ctx.create(BvExpr::Div, _x, ctx.create(BvExpr::Ite, _x, _x, _c0)));
  candidates.push_back(ctx.create(BvExpr::Div, _x, ctx.create(BvExpr::Ite, _x, _c0, _x)));
  candidates.push_back(ctx.create(BvExpr::Div, _c0, ctx.create(BvExpr::Minus, _x)));
  candidates.push_back(ctx.create(BvExpr::Div, _c0, ctx.create(BvExpr::Not, _x)));
  candidates.push_back(ctx.create(BvExpr::Div, _c0, ctx.create(BvExpr::Add, _x, _x)));
  candidates.push_back(ctx.create(BvExpr::Div, _c0, ctx.create(BvExpr::Sub, _x, _c1)));
  candidates.push_back(ctx.create(BvExpr::Div, _c0, ctx.create(BvExpr::Sub, _c1, _x)));
  candidates.push_back(ctx.create(BvExpr::Div, _c0, ctx.create(BvExpr::Mul, _x, _x)));
  candidates.push_back(ctx.create(BvExpr::Div, _c0, ctx.create(BvExpr::Div, _x, _c1)));
  candidates.push_back(ctx.create(BvExpr::Div, _c0, ctx.create(BvExpr::Div, _c1, _x)));
  candidates.push_back(ctx.create(BvExpr::Div, _c0, ctx.create(BvExpr::Mod, _x, _c1)));
  candidates.push_back(ctx.create(BvExpr::Div, _c0, ctx.create(BvExpr::Mod, _c1, _x)));
  candidates.push_back(ctx.create(BvExpr::Div, _c0, ctx.create(BvExpr::MulMod, _x, _x, _c1)));
  candidates.push_back(ctx.create(BvExpr::Div, _c0, ctx.create(BvExpr::Ite, _x, _x, _c1)));
  candidates.push_back(ctx.create(BvExpr::Div, _c0, ctx.create(BvExpr::Ite, _x, _c1, _x)));
  candidates.push_back(ctx.create(BvExpr::Mod, ctx.create(BvExpr::Minus, _x), _x));
  candidates.push_back(ctx.create(BvExpr::Mod, ctx.create(BvExpr::Minus, _x), _c0));
  candidates.push_back(ctx.create(BvExpr::Mod, ctx.create(BvExpr::Not, _x), _x));
  candidates.push_back(ctx.create(BvExpr::Mod, ctx.create(BvExpr::Not, _x), _c0));
  candidates.push_back(ctx.create(BvExpr::Mod, ctx.create(BvExpr::Add, _x, _x), _x));
  candidates.push_back(ctx.create(BvExpr::Mod, ctx.create(BvExpr::Add, _x, _x), _c0));
  candidates.push_back(ctx.create(BvExpr::Mod, ctx.create(BvExpr::Sub, _x, _c0), _x));
  candidates.push_back(ctx.create(BvExpr::Mod, ctx.create(BvExpr::Sub, _x, _c0), _c1));
  candidates.push_back(ctx.create(BvExpr::Mod, ctx.create(BvExpr::Sub, _c0, _x), _x));
  candidates.push_back(ctx.create(BvExpr::Mod, ctx.create(BvExpr::Sub, _c0, _x), _c1));
  candidates.push_back(ctx.create(BvExpr::Mod, ctx.create(BvExpr::Div, _x, _c0), _x));
  candidates.push_back(ctx.create(BvExpr::Mod, ctx.create(BvExpr::Div, _x, _c0), _c1));
  candidates.push_back(ctx.create(BvExpr::Mod, ctx.create(BvExpr::Div, _c0, _x), _x));
  candidates.push_back(ctx.create(BvExpr::Mod, ctx.create(BvExpr::Div, _c0, _x), _c1));
  candidates.push_back(ctx.create(BvExpr::Mod, ctx.create(BvExpr::Mod, _x, _c0), _x));
  candidates.push_back(ctx.create(BvExpr::Mod, ctx.create(BvExpr::Mod, _x, _c0), _c1));
  candidates.push_back(ctx.create(BvExpr::Mod, ctx.create(BvExpr::Mod, _c0, _x), _x));
  candidates.push_back(ctx.create(BvExpr::Mod, ctx.create(BvExpr::Mod, _c0, _x), _c1));
  candidates.push_back(ctx.create(BvExpr::Mod, ctx.create(BvExpr::MulMod, _x, _x, _c0), _x));
  candidates.push_back(ctx.create(BvExpr::Mod, ctx.create(BvExpr::MulMod, _x, _x, _c0), _c1));
  candidates.push_back(ctx.create(BvExpr::Mod, ctx.create(BvExpr::Ite, _x, _x, _c0), _x));
  candidates.push_back(ctx.create(BvExpr::Mod, ctx.create(BvExpr::Ite, _x, _x, _c0), _c1));
  candidates.push_back(ctx.create(BvExpr::Mod, ctx.create(BvExpr::Ite, _x, _c0, _x), _x));
  candidates.push_back(ctx.create(BvExpr::Mod, ctx.create(BvExpr::Ite, _x, _c0, _x), _c1));
  candidates.push_back(ctx.create(BvExpr::Mod, _x, ctx.create(BvExpr::Not, _x)));
  candidates.push_back(ctx.create(BvExpr::Mod, _x, ctx.create(BvExpr::Add, _x, _x)));
  candidates.push_back(ctx.create(BvExpr::Mod, _x, ctx.create(BvExpr::Sub, _x, _c0)));
  candidates.push_back(ctx.create(BvExpr::Mod, _x, ctx.create(BvExpr::Sub, _c0, _x)));
  candidates.push_back(ctx.create(BvExpr::Mod, _x, ctx.create(BvExpr::Mul, _x, _x)));
  candidates.push_back(ctx.create(BvExpr::Mod, _x, ctx.create(BvExpr::Div, _x, _c0)));
  candidates.push_back(ctx.create(BvExpr::Mod, _x, ctx.create(BvExpr::Div, _c0, _x)));
  candidates.push_back(ctx.create(BvExpr::Mod, _x, ctx.create(BvExpr::Mod, _x, _c0)));
  candidates.push_back(ctx.create(BvExpr::Mod, _x, ctx.create(BvExpr::Mod, _c0, _x)));
  candidates.push_back(ctx.create(BvExpr::Mod, _x, ctx.create(BvExpr::MulMod, _x, _x, _c0)));
  candidates.push_back(ctx.create(BvExpr::Mod, _x, ctx.create(BvExpr::Ite, _x, _x, _c0)));
  candidates.push_back(ctx.create(BvExpr::Mod, _x, ctx.create(BvExpr::Ite, _x, _c0, _x)));
  candidates.push_back(ctx.create(BvExpr::Mod, _c0, ctx.create(BvExpr::Not, _x)));
  candidates.push_back(ctx.create(BvExpr::Mod, _c0, ctx.create(BvExpr::Add, _x, _x)));
  candidates.push_back(ctx.create(BvExpr::Mod, _c0, ctx.create(BvExpr::Sub, _x, _c1)));
  candidates.push_back(ctx.create(BvExpr::Mod, _c0, ctx.create(BvExpr::Sub, _c1, _x)));
  candidates.push_back(ctx.create(BvExpr::Mod, _c0, ctx.create(BvExpr::Mul, _x, _x)));
  candidates.push_back(ctx.create(BvExpr::Mod, _c0, ctx.create(BvExpr::Div, _x, _c1)));
  candidates.push_back(ctx.create(BvExpr::Mod, _c0, ctx.create(BvExpr::Div, _c1, _x)));
  candidates.push_back(ctx.create(BvExpr::Mod, _c0, ctx.create(BvExpr::Mod, _x, _c1)));
  candidates.push_back(ctx.create(BvExpr::Mod, _c0, ctx.create(BvExpr::Mod, _c1, _x)));
  candidates.push_back(ctx.create(BvExpr::Mod, _c0, ctx.create(BvExpr::MulMod, _x, _x, _c1)));
  candidates.push_back(ctx.create(BvExpr::Mod, _c0, ctx.create(BvExpr::Ite, _x, _x, _c1)));
  candidates.push_back(ctx.create(BvExpr::Mod, _c0, ctx.create(BvExpr::Ite, _x, _c1, _x)));
  candidates.push_back(ctx.create(BvExpr::MulMod, ctx.create(BvExpr::Minus, _x), _x, _c0));
  candidates.push_back(ctx.create(BvExpr::MulMod, ctx.create(BvExpr::Minus, _x), _c0, _x));
  candidates.push_back(ctx.create(BvExpr::MulMod, ctx.create(BvExpr::Not, _x), _x, _c0));
  candidates.push_back(ctx.create(BvExpr::MulMod, ctx.create(BvExpr::Not, _x), _c0, _x));
  candidates.push_back(ctx.create(BvExpr::MulMod, ctx.create(BvExpr::Add, _x, _x), _x, _c0));
  candidates.push_back(ctx.create(BvExpr::MulMod, ctx.create(BvExpr::Add, _x, _x), _c0, _x));
  candidates.push_back(ctx.create(BvExpr::MulMod, ctx.create(BvExpr::Sub, _x, _c0), _x, _c1));
  candidates.push_back(ctx.create(BvExpr::MulMod, ctx.create(BvExpr::Sub, _x, _c0), _c1, _x));
  candidates.push_back(ctx.create(BvExpr::MulMod, ctx.create(BvExpr::Sub, _c0, _x), _x, _c1));
  candidates.push_back(ctx.create(BvExpr::MulMod, ctx.create(BvExpr::Sub, _c0, _x), _c1, _x));
  candidates.push_back(ctx.create(BvExpr::MulMod, ctx.create(BvExpr::Mul, _x, _x), _x, _c0));
  candidates.push_back(ctx.create(BvExpr::MulMod, ctx.create(BvExpr::Mul, _x, _x), _c0, _x));
  candidates.push_back(ctx.create(BvExpr::MulMod, ctx.create(BvExpr::Div, _x, _c0), _x, _c1));
  candidates.push_back(ctx.create(BvExpr::MulMod, ctx.create(BvExpr::Div, _x, _c0), _c1, _x));
  candidates.push_back(ctx.create(BvExpr::MulMod, ctx.create(BvExpr::Div, _c0, _x), _x, _c1));
  candidates.push_back(ctx.create(BvExpr::MulMod, ctx.create(BvExpr::Div, _c0, _x), _c1, _x));
  candidates.push_back(ctx.create(BvExpr::MulMod, ctx.create(BvExpr::Mod, _x, _c0), _x, _c1));
  candidates.push_back(ctx.create(BvExpr::MulMod, ctx.create(BvExpr::Mod, _x, _c0), _c1, _x));
  candidates.push_back(ctx.create(BvExpr::MulMod, ctx.create(BvExpr::Mod, _c0, _x), _x, _c1));
  candidates.push_back(ctx.create(BvExpr::MulMod, ctx.create(BvExpr::Mod, _c0, _x), _c1, _x));
  candidates.push_back(ctx.create(BvExpr::MulMod, ctx.create(BvExpr::MulMod, _x, _x, _c0), _x, _c1));
  candidates.push_back(ctx.create(BvExpr::MulMod, ctx.create(BvExpr::MulMod, _x, _x, _c0), _c1, _x));
  candidates.push_back(ctx.create(BvExpr::MulMod, ctx.create(BvExpr::Ite, _x, _x, _c0), _x, _c1));
  candidates.push_back(ctx.create(BvExpr::MulMod, ctx.create(BvExpr::Ite, _x, _x, _c0), _c1, _x));
  candidates.push_back(ctx.create(BvExpr::MulMod, ctx.create(BvExpr::Ite, _x, _c0, _x), _x, _c1));
  candidates.push_back(ctx.create(BvExpr::MulMod, ctx.create(BvExpr::Ite, _x, _c0, _x), _c1, _x));
  candidates.push_back(ctx.create(BvExpr::MulMod, _x, ctx.create(BvExpr::Minus, _x), _c0));
  candidates.push_back(ctx.create(BvExpr::MulMod, _x, ctx.create(BvExpr::Not, _x), _c0));
  candidates.push_back(ctx.create(BvExpr::MulMod, _x, ctx.create(BvExpr::Add, _x, _x), _c0));
  candidates.push_back(ctx.create(BvExpr::MulMod, _x, ctx.create(BvExpr::Sub, _x, _c0), _c1));
  candidates.push_back(ctx.create(BvExpr::MulMod, _x, ctx.create(BvExpr::Sub, _c0, _x), _c1));
  candidates.push_back(ctx.create(BvExpr::MulMod, _x, ctx.create(BvExpr::Mul, _x, _x), _c0));
  candidates.push_back(ctx.create(BvExpr::MulMod, _x, ctx.create(BvExpr::Div, _x, _c0), _c1));
  candidates.push_back(ctx.create(BvExpr::MulMod, _x, ctx.create(BvExpr::Div, _c0, _x), _c1));
  candidates.push_back(ctx.create(BvExpr::MulMod, _x, ctx.create(BvExpr::Mod, _x, _c0), _c1));
  candidates.push_back(ctx.create(BvExpr::MulMod, _x, ctx.create(BvExpr::Mod, _c0, _x), _c1));
  candidates.push_back(ctx.create(BvExpr::MulMod, _x, ctx.create(BvExpr::MulMod, _x, _x, _c0), _c1));
  candidates.push_back(ctx.create(BvExpr::MulMod, _x, ctx.create(BvExpr::Ite, _x, _x, _c0), _c1));
  candidates.push_back(ctx.create(BvExpr::MulMod, _x, ctx.create(BvExpr::Ite, _x, _c0, _x), _c1));
  candidates.push_back(ctx.create(BvExpr::MulMod, _x, _x, ctx.create(BvExpr::Not, _x)));
  candidates.push_back(ctx.create(BvExpr::MulMod, _x, _x, ctx.create(BvExpr::Add, _x, _x)));
  candidates.push_back(ctx.create(BvExpr::MulMod, _x, _x, ctx.create(BvExpr::Sub, _x, _c0)));
  candidates.push_back(ctx.create(BvExpr::MulMod, _x, _x, ctx.create(BvExpr::Sub, _c0, _x)));
  candidates.push_back(ctx.create(BvExpr::MulMod, _x, _x, ctx.create(BvExpr::Mul, _x, _x)));
  candidates.push_back(ctx.create(BvExpr::MulMod, _x, _x, ctx.create(BvExpr::Div, _x, _c0)));
  candidates.push_back(ctx.create(BvExpr::MulMod, _x, _x, ctx.create(BvExpr::Div, _c0, _x)));
  candidates.push_back(ctx.create(BvExpr::MulMod, _x, _x, ctx.create(BvExpr::Mod, _x, _c0)));
  candidates.push_back(ctx.create(BvExpr::MulMod, _x, _x, ctx.create(BvExpr::Mod, _c0, _x)));
  candidates.push_back(ctx.create(BvExpr::MulMod, _x, _x, ctx.create(BvExpr::MulMod, _x, _x, _c0)));
  candidates.push_back(ctx.create(BvExpr::MulMod, _x, _x, ctx.create(BvExpr::Ite, _x, _x, _c0)));
  candidates.push_back(ctx.create(BvExpr::MulMod, _x, _x, ctx.create(BvExpr::Ite, _x, _c0, _x)));
  candidates.push_back(ctx.create(BvExpr::Ite, ctx.create(BvExpr::Minus, _x), _x, _c0));
  candidates.push_back(ctx.create(BvExpr::Ite, ctx.create(BvExpr::Minus, _x), _c0, _x));
  candidates.push_back(ctx.create(BvExpr::Ite, ctx.create(BvExpr::Not, _x), _x, _c0));
  candidates.push_back(ctx.create(BvExpr::Ite, ctx.create(BvExpr::Not, _x), _c0, _x));
  candidates.push_back(ctx.create(BvExpr::Ite, ctx.create(BvExpr::Add, _x, _x), _x, _c0));
  candidates.push_back(ctx.create(BvExpr::Ite, ctx.create(BvExpr::Add, _x, _x), _c0, _x));
  candidates.push_back(ctx.create(BvExpr::Ite, ctx.create(BvExpr::Sub, _x, _c0), _x, _c1));
  candidates.push_back(ctx.create(BvExpr::Ite, ctx.create(BvExpr::Sub, _x, _c0), _c1, _x));
  candidates.push_back(ctx.create(BvExpr::Ite, ctx.create(BvExpr::Sub, _c0, _x), _x, _c1));
  candidates.push_back(ctx.create(BvExpr::Ite, ctx.create(BvExpr::Sub, _c0, _x), _c1, _x));
  candidates.push_back(ctx.create(BvExpr::Ite, ctx.create(BvExpr::Mul, _x, _x), _x, _c0));
  candidates.push_back(ctx.create(BvExpr::Ite, ctx.create(BvExpr::Mul, _x, _x), _c0, _x));
  candidates.push_back(ctx.create(BvExpr::Ite, ctx.create(BvExpr::Div, _x, _c0), _x, _c1));
  candidates.push_back(ctx.create(BvExpr::Ite, ctx.create(BvExpr::Div, _x, _c0), _c1, _x));
  candidates.push_back(ctx.create(BvExpr::Ite, ctx.create(BvExpr::Div, _c0, _x), _x, _c1));
  candidates.push_back(ctx.create(BvExpr::Ite, ctx.create(BvExpr::Div, _c0, _x), _c1, _x));
  candidates.push_back(ctx.create(BvExpr::Ite, ctx.create(BvExpr::Mod, _x, _c0), _x, _c1));
  candidates.push_back(ctx.create(BvExpr::Ite, ctx.create(BvExpr::Mod, _x, _c0), _c1, _x));
  candidates.push_back(ctx.create(BvExpr::Ite, ctx.create(BvExpr::Mod, _c0, _x), _x, _c1));
  candidates.push_back(ctx.create(BvExpr::Ite, ctx.create(BvExpr::Mod, _c0, _x), _c1, _x));
  candidates.push_back(ctx.create(BvExpr::Ite, ctx.create(BvExpr::MulMod, _x, _x, _c0), _x, _c1));
  candidates.push_back(ctx.create(BvExpr::Ite, ctx.create(BvExpr::MulMod, _x, _x, _c0), _c1, _x));
  candidates.push_back(ctx.create(BvExpr::Ite, ctx.create(BvExpr::Ite, _x, _x, _c0), _x, _c1));
  candidates.push_back(ctx.create(BvExpr::Ite, ctx.create(BvExpr::Ite, _x, _x, _c0), _c1, _x));
  candidates.push_back(ctx.create(BvExpr::Ite, ctx.create(BvExpr::Ite, _x, _c0, _x), _x, _c1));
  candidates.push_back(ctx.create(BvExpr::Ite, ctx.create(BvExpr::Ite, _x, _c0, _x), _c1, _x));
  candidates.push_back(ctx.create(BvExpr::Ite, _x, ctx.create(BvExpr::Minus, _x), _x));
  candidates.push_back(ctx.create(BvExpr::Ite, _x, ctx.create(BvExpr::Minus, _x), _c0));
  candidates.push_back(ctx.create(BvExpr::Ite, _x, ctx.create(BvExpr::Not, _x), _x));
  candidates.push_back(ctx.create(BvExpr::Ite, _x, ctx.create(BvExpr::Not, _x), _c0));
  candidates.push_back(ctx.create(BvExpr::Ite, _x, ctx.create(BvExpr::Add, _x, _x), _x));
  candidates.push_back(ctx.create(BvExpr::Ite, _x, ctx.create(BvExpr::Add, _x, _x), _c0));
  candidates.push_back(ctx.create(BvExpr::Ite, _x, ctx.create(BvExpr::Sub, _x, _c0), _x));
  candidates.push_back(ctx.create(BvExpr::Ite, _x, ctx.create(BvExpr::Sub, _x, _c0), _c1));
  candidates.push_back(ctx.create(BvExpr::Ite, _x, ctx.create(BvExpr::Sub, _c0, _x), _x));
  candidates.push_back(ctx.create(BvExpr::Ite, _x, ctx.create(BvExpr::Sub, _c0, _x), _c1));
  candidates.push_back(ctx.create(BvExpr::Ite, _x, ctx.create(BvExpr::Mul, _x, _x), _x));
  candidates.push_back(ctx.create(BvExpr::Ite, _x, ctx.create(BvExpr::Mul, _x, _x), _c0));
  candidates.push_back(ctx.create(BvExpr::Ite, _x, ctx.create(BvExpr::Div, _x, _c0), _x));
  candidates.push_back(ctx.create(BvExpr::Ite, _x, ctx.create(BvExpr::Div, _x, _c0), _c1));
  candidates.push_back(ctx.create(BvExpr::Ite, _x, ctx.create(BvExpr::Div, _c0, _x), _x));
  candidates.push_back(ctx.create(BvExpr::Ite, _x, ctx.create(BvExpr::Div, _c0, _x), _c1));
  candidates.push_back(ctx.create(BvExpr::Ite, _x, ctx.create(BvExpr::Mod, _x, _c0), _x));
  candidates.push_back(ctx.create(BvExpr::Ite, _x, ctx.create(BvExpr::Mod, _x, _c0), _c1));
  candidates.push_back(ctx.create(BvExpr::Ite, _x, ctx.create(BvExpr::Mod, _c0, _x), _x));
  candidates.push_back(ctx.create(BvExpr::Ite, _x, ctx.create(BvExpr::Mod, _c0, _x), _c1));
  candidates.push_back(ctx.create(BvExpr::Ite, _x, ctx.create(BvExpr::MulMod, _x, _x, _c0), _x));
  candidates.push_back(ctx.create(BvExpr::Ite, _x, ctx.create(BvExpr::MulMod, _x, _x, _c0), _c1));
  candidates.push_back(ctx.create(BvExpr::Ite, _x, ctx.create(BvExpr::Ite, _x, _x, _c0), _x));
  candidates.push_back(ctx.create(BvExpr::Ite, _x, ctx.create(BvExpr::Ite, _x, _x, _c0), _c1));
  candidates.push_back(ctx.create(BvExpr::Ite, _x, ctx.create(BvExpr::Ite, _x, _c0, _x), _x));
  candidates.push_back(ctx.create(BvExpr::Ite, _x, ctx.create(BvExpr::Ite, _x, _c0, _x), _c1));
  candidates.push_back(ctx.create(BvExpr::Ite, _x, _x, ctx.create(BvExpr::Minus, _x)));
  candidates.push_back(ctx.create(BvExpr::Ite, _x, _x, ctx.create(BvExpr::Not, _x)));
  candidates.push_back(ctx.create(BvExpr::Ite, _x, _x, ctx.create(BvExpr::Add, _x, _x)));
  candidates.push_back(ctx.create(BvExpr::Ite, _x, _x, ctx.create(BvExpr::Sub, _x, _c0)));
  candidates.push_back(ctx.create(BvExpr::Ite, _x, _x, ctx.create(BvExpr::Sub, _c0, _x)));
  candidates.push_back(ctx.create(BvExpr::Ite, _x, _x, ctx.create(BvExpr::Mul, _x, _x)));
  candidates.push_back(ctx.create(BvExpr::Ite, _x, _x, ctx.create(BvExpr::Div, _x, _c0)));
  candidates.push_back(ctx.create(BvExpr::Ite, _x, _x, ctx.create(BvExpr::Div, _c0, _x)));
  candidates.push_back(ctx.create(BvExpr::Ite, _x, _x, ctx.create(BvExpr::Mod, _x, _c0)));
  candidates.push_back(ctx.create(BvExpr::Ite, _x, _x, ctx.create(BvExpr::Mod, _c0, _x)));
  candidates.push_back(ctx.create(BvExpr::Ite, _x, _x, ctx.create(BvExpr::MulMod, _x, _x, _c0)));
  candidates.push_back(ctx.create(BvExpr::Ite, _x, _x, ctx.create(BvExpr::Ite, _x, _x, _c0)));
  candidates.push_back(ctx.create(BvExpr::Ite, _x, _x, ctx.create(BvExpr::Ite, _x, _c0, _x)));
  candidates.push_back(ctx.create(BvExpr::Ite, _x, _c0, ctx.create(BvExpr::Minus, _x)));
  candidates.push_back(ctx.create(BvExpr::Ite, _x, _c0, ctx.create(BvExpr::Not, _x)));
  candidates.push_back(ctx.create(BvExpr::Ite, _x, _c0, ctx.create(BvExpr::Add, _x, _x)));
  candidates.push_back(ctx.create(BvExpr::Ite, _x, _c0, ctx.create(BvExpr::Sub, _x, _c1)));
  candidates.push_back(ctx.create(BvExpr::Ite, _x, _c0, ctx.create(BvExpr::Sub, _c1, _x)));
  candidates.push_back(ctx.create(BvExpr::Ite, _x, _c0, ctx.create(BvExpr::Mul, _x, _x)));
  candidates.push_back(ctx.create(BvExpr::Ite, _x, _c0, ctx.create(BvExpr::Div, _x, _c1)));
  candidates.push_back(ctx.create(BvExpr::Ite, _x, _c0, ctx.create(BvExpr::Div, _c1, _x)));
  candidates.push_back(ctx.create(BvExpr::Ite, _x, _c0, ctx.create(BvExpr::Mod, _x, _c1)));
  candidates.push_back(ctx.create(BvExpr::Ite, _x, _c0, ctx.create(BvExpr::Mod, _c1, _x)));
  candidates.push_back(ctx.create(BvExpr::Ite, _x, _c0, ctx.create(BvExpr::MulMod, _x, _x, _c1)));
  candidates.push_back(ctx.create(BvExpr::Ite, _x, _c0, ctx.create(BvExpr::Ite, _x, _x, _c1)));
  candidates.push_back(ctx.create(BvExpr::Ite, _x, _c0, ctx.create(BvExpr::Ite, _x, _c1, _x)));
}
